on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: monterail/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter test
